Name:	#Project Name, this is a required field
Is_Private:  #Project_Privacy setting, options are 0, 1, or 2, If the field is left empty, the default value 0 will be used.
#0: Company-Wide (default)
#1: Confidential (authorized users will have full access, other users will have no access)
#2: Restricted (authorized users will have full access, other users will have restricted access)
#Enter file name for one of the two fields below based on the Project_Privacy setting.
File_Name:  #file name of the h5ad file (required for Company-wide projects), the file should be saved in the public celldepot data folder. 
#If the data is processed by scRNASequest pipeline, the h5ad file will be automatically saved to the public celldepot data folder.
File_Name_Private:  #full file path of the h5ad file (required for Confidential/Restricted projects). The file path will be hidden to unauthorized users CellDepot.
#Other attributes of the project, all the fields below are optional. Pleaes fill in as many attributes as possible to make the project more informative.
Description:	#Project Description. This attribute supports multiple lines such as paragraph (Use \n for new line).
Custom Accession:	#e.g., SCP8888
Species:	#e.g., Human, Mouse, Rat
Diseases:	#e.g., Alzheimer's Disease, Multiple Sclerosis
Experiment_Type: #e.g. scRNA, or multiple values: ["scRNA","CosMx"]
URL:	# URL of the data source if applicable
Notes:	#Project Notes
Title:	#Publication Title
Year::	#Publication Year
DOI:	#DOI
PMCID:	#PMC ID
PMID:	#PubMed ID
User_Email:	#	Email of the Project Owner, e.g.  john@example.com
Is_Private_Users: #Email addresses of the authorized users.This value will be used if Is_Private is 1 (confidential) or 2 (restricted).
